site_name: FleetingViews
repo_url: https://github.com/ArellanoBrunoc/FleetingViews
repo_name: ArellanoBrunoc/FleetingViews
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
theme:
  name: material  
  icon:
    repo: fontawesome/brands/github

  palette:
    scheme: slate
    primary: blue

  features:
    - content.code.copy
    - content.code.annotate
    - navigation.footer
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Features: features.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format